title: cprima.net
email: cprior@gmail.com
author: Christian Prior-Mamulyan
description: >-
  A sysadmin's notepad, a publishing hub and more.
description_de: >- # this means to ignore newlines until "baseurl:"
  A sysadmin's notepad, a publishing hub and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
host: 0.0.0.0
mailchimp-audience: "448978308e"
mailchimp-user: "7397e207aec2e90684a8a69be&amp"
mailchimp-formaction: "https://gmail.us10.list-manage.com/subscribe/post?u=7397e207aec2e90684a8a69be&amp;id=448978308e"
copyright-license: "Copyright © 2024 Christian Prior-Mamulyan · License CC BY-SA 4.0"

# Build settings
markdown: kramdown
highlighter: rouge
#markdown: Pandoc
#plugins:
#  - jekyll-feed
future: true
timezone: Europe/Berlin
permalink: /:categories/:year/:month/:day/:title:output_ext

feed:
  path: /biz/marketing/website/feed.xml

source: .
layouts_dir: ./biz/marketing/website/_layouts
includes_dir: ./biz/marketing/website/_includes
destination: ./biz/marketing/website/_site
data_dir: ./dat
sass:
  sass_dir: ./biz/marketing/website/assets/_sass

exclude:
  - data
  - tec/phy/*/settings
  - tec/phy/**/resources/**/*.pdf

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  - scope:
      path: "app/log/building-blocks"
      type: "posts" #index.md is of type application_logical_building-blocks
    values:
      permalink: /app/log/building-blocks/:title.html
      categories: application_logical_building-blocks
  - scope:
      path: "tec/phy/*/README.md"
      type: "pages"
    values:
      categories: technology-physical
      layout: taptc
  - scope:
      path: "tec/phy/*/*/README.md"
      type: "pages"
    values:
      categories: technology-physical
      layout: taptc
  - scope:
      path: "tec/phy/building-blocks"
      type: "posts" #index.md is of type technology-physical_building-blocks
    values:
      permalink: /tec/phy/building-blocks/:title.html
      #categories: technology-physical_building-blocks
  - scope:
      path: "biz/*/*/*/README.md"
      type: "pages"
    values:
      categories: business
      layout: bapro
