#https://cloud.google.com/functions/docs/calling/storage#functions-calling-storage-python

gcloud functions deploy hello_gcs \
--runtime python39 \
--trigger-resource YOUR_TRIGGER_BUCKET_NAME \
--trigger-event google.storage.object.finalize